title: <img src="doc/uhm-gitclubs-logo-final.jpg"> UH Manoa GitClubs
description: Club Browsing Made Easy for the UH Community
theme: jekyll-theme-cayman
github:
  is_project_page: true
  organization_url: https://github.com/uhm-gitclubs/uhm-gitclubs