title: <img src="doc/logoheader.png" alt="GitClubs" width="400px"/>
description: Club Browsing Made Easy for the UH Community
theme: jekyll-theme-cayman
github:
  is_project_page: true
  organization_url: https://github.com/uhm-gitclubs/uhm-gitclubs